spring:
  application:
    name: users-service
  cloud:
    config:
      discovery:
        enabled: true
        serviceId: cloud-config
      fail-fast: true
      profile: local
      request-connect-timeout: 10
  config:
    import: configserver:http://localhost:8762
  lifecycle:
    timeout-per-shutdown-phase: 30s
#  webflux:
#    base-path: '/api/users-service'
  liquibase:
    url: jdbc:postgresql://localhost:5432/microservice?schema=users_service
    default-schema: users_service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    webclient:
      enabled: true

management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
