spring:
  application:
    name: gateway-service
  cloud:
    config:
      discovery:
        enabled: true
        serviceId: cloud-config
      fail-fast: true
      profile: local
      request-connect-timeout: 10
  config:
    import: optional:configserver:http://localhost:8762
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    webclient:
      enabled: true

management:
  info:
    env:
      enabled: true
  endpoint:
    info:
      enabled: true
    health:
      probes:
        enabled: true
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /manage
